###
GET http://localhost:5000/api/

###                                         SIGN UP
POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "name": "bbb",
    "lastname": "b",
    "email": "b@b.com",
    "password": "b"
}

###                                         SIGN IN
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "aaa"
}


###                                AUTHORIZATION (Protected Test Route)
GET http://localhost:5000/api/testroute
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTc3NmM5ZGVjN2E3OTI3OTg4Y2QwMzQiLCJpYXQiOjE1ODQ4ODkxMzl9.4OuKWpr9uoEJqsSTqWtQ_-W94TIjCZE98RVrUq16yHM

{
    "email": "a@a.com",
    "password": "bbb"
}